### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by 89z** [ruby/securerandom#1]
where is the documentation for this gem? Previously it was here:

https://ruby-doc.org/stdlib-2.5.8/libdoc/securerandom/rdoc

**Comment by 89z** [comment]
I think this is it:

https://rubydoc.info/github/ruby/securerandom

**Comment by hsbt** [comment]
Here https://docs.ruby-lang.org/en/master/SecureRandom.html

**Comment by 89z** [comment]
I dont know if its intentional, but it seems this page should exist, but doesnt:

https://ruby-doc.org/core/SecureRandom.html
