### ISSUE TITLE
Release 0.1.2 with changes shipped in Ruby 3.1

### ISSUE THREAD

**Issue by headius** [ruby/securerandom#10]
Ruby 3.1 was shipped with changes to securerandom that have not been released in any gem. Ruby 3.1 reports that it is shipping securerandom 0.1.1 but the sources are newer.

We need a release of securerandom 0.1.2 to have a gem that matches Ruby 3.1.

See https://bugs.ruby-lang.org/issues/18169

**Comment by hsbt** [comment]
I'm going to handle this.

**Comment by headius** [comment]
Thank you!
