### ISSUE TITLE
Allow custom source, i.e. for ALPHANUMERIC?

### ISSUE THREAD

**Issue by pil0u** [ruby/securerandom#2]
Hello team, thanks a lot for the tool.

I would like to generate a string with only letters. In SecureRandom, the `alphanumeric` method depends on the `ALPHANUMERIC` constant. The Rails team has tweaked it a little by adding the `base36` and `base58` methods.

Would adding the ability to customize the source Array to securely generate random strings be a bad idea?
If yes, what would be the most effective way to generate a random string made only of letters?

Thanks!

**Comment by Hampei** [comment]
This  would actually be as  easy as making the choose method public. And I for one am very much in favour. 

In the meantime using the private method should be quite safe with a simple spec:

https://github.com/ruby/securerandom/blob/137ff0deb6080b782177c1d194df7acfccb9da0a/lib/random/formatter.rb#L215

**Comment by avi-berkowitz-instacart** [comment]
Are there any updates on making `choose` public?

**Comment by h0jeZvgoxFepBQ2C** [comment]
Bump, would be in favour of it!

**Comment by nobu** [comment]
[`Random#alphanumeric` now has `chars:` optional keyword argument](b2e9309e0dc4f3af4ae84ec476b5c065d2d60ccf)
