### ISSUE TITLE
JRuby support

### ISSUE THREAD

**Issue by headius** [ruby/securerandom#9]
JRuby has a native extension for this and we would like to be able to use the gem. I will handle making the changes necessary, including evaluating whether or not to keep the JRuby extension.

I believe this gem should work ok on JRuby as-is, so the main question is whether we want to lose our ext version.

**Comment by steakknife** [comment]
@headius Necro ping. Perhaps they would discuss a weak dependency on a JRuby-maintained gem?

```ruby
begin
  require 'securerandom-java' if RUBY_ENGINE == 'jruby'
rescue LoadError
end
```

That way, only low-level code remains in -java and no maintenance for MRI.

Btw: [JNI in Rust](https://docs.rs/jni/latest/jni/)

**Comment by headius** [comment]
JRuby 9.4 shipped with securerandom gem, but had some bugs that caused it to not work properly. JRuby 9.4.1 will be released soon with some fixes. I think this issue can be closed.
